//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invary.IvyMediaDownloader {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceSet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSet() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Invary.IvyMediaDownloader.ResourceSet", typeof(ResourceSet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add to download que に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripAddNew_AddDownQue {
            get {
                return ResourceManager.GetString("ContextMenuStripAddNew_AddDownQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to download que and start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripAddNew_AddDownQueStartNow {
            get {
                return ResourceManager.GetString("ContextMenuStripAddNew_AddDownQueStartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripAddNew_ClearSelected {
            get {
                return ResourceManager.GetString("ContextMenuStripAddNew_ClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Args に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_Args {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ClearCompleted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_ClearCompleted {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_ClearCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CopyUrl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_CopyUrl {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeleteSelected(fromDB) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_DeleteSelectedFromDB {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_DeleteSelectedFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeleteSelected(onlyView) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_DeleteSelectedFromView {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_DeleteSelectedFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EditFolderName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_EditFolderName {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_EditFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   KillSelected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_KillSelected {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_KillSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ResetCompletedFlag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_ResetCompletedFlag {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_ResetCompletedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_SelectAll {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SetCompletedFlag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_SetCompletedFlag {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_SetCompletedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_StartAll {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StartSelected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_StartSelected {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_StartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StopAll に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_StopAll {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StopSelected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripMain_StopSelected {
            get {
                return ResourceManager.GetString("ContextMenuStripMain_StopSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add to download que に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripSubscribed_AddDownQue {
            get {
                return ResourceManager.GetString("ContextMenuStripSubscribed_AddDownQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsubscribe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripSubscribed_Unsubscribe {
            get {
                return ResourceManager.GetString("ContextMenuStripSubscribed_Unsubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear selected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripSubscribedPrep_ClearSelected {
            get {
                return ResourceManager.GetString("ContextMenuStripSubscribedPrep_ClearSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subscribe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ContextMenuStripSubscribedPrep_Subscribe {
            get {
                return ResourceManager.GetString("ContextMenuStripSubscribedPrep_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If subscribed item, this change will be ignored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditFolderNameForm_Description {
            get {
                return ResourceManager.GetString("EditFolderNameForm_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save folder name (not full path) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditFolderNameForm_Name {
            get {
                return ResourceManager.GetString("EditFolderNameForm_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit save folder name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditFolderNameForm_Title {
            get {
                return ResourceManager.GetString("EditFolderNameForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid command line args に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidCommandlineOption {
            get {
                return ResourceManager.GetString("InvalidCommandlineOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR: ffmpeg.exe is not exists ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelFFmpeg_Error {
            get {
                return ResourceManager.GetString("LabelFFmpeg_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ffmpeg.exe is found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelFFmpeg_Found {
            get {
                return ResourceManager.GetString("LabelFFmpeg_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ERROR: yt-dlp.exe is not exists ! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelYtDlp_Error {
            get {
                return ResourceManager.GetString("LabelYtDlp_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yt-dlp.exe is found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LabelYtDlp_Found {
            get {
                return ResourceManager.GetString("LabelYtDlp_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Arg {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETA に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_ETA {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Folder {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_No {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Progress {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Size {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Speed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Speed {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Status {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Title {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewDownloadColumns_Url {
            get {
                return ResourceManager.GetString("ListViewDownloadColumns_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yt-dlp arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_Args {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_Author {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_Description {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_FolderName {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_No {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_Status {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_Title {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribedColumns_Url {
            get {
                return ResourceManager.GetString("ListViewSubscribedColumns_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yt-dlp arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_Args {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_Author {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Description に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_Description {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_FolderName {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_No {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_Status {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_Title {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewSubscribePrepColumns_Url {
            get {
                return ResourceManager.GetString("ListViewSubscribePrepColumns_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yt-dlp arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Args {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Author に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Author {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Duration {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Folder {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Id {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_No {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Status {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Title {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewVideoInfo_Url {
            get {
                return ResourceManager.GetString("ListViewVideoInfo_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear completed. Remove the downloaded item from the view, not from database. You cannot download this item again, until clear completed flag. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_ClearCompleted {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_ClearCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy URL to clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_CopyUrl {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected items from DB. Remove item from the view and database. You can download item again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_DeleteSelectedFromDB {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_DeleteSelectedFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete selected items from view. Remove item from the view, not from database. If item is not download completed, next time you can see this item in the view. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_DeleteSelectedFromView {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_DeleteSelectedFromView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit folder name. Edit the output folder. If the items are subscribed and the output destination folder is set, the subscribed item settings will take priority. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_EditFolderName {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_EditFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kill selected. Force the download to stop. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_KillSelected {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_KillSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset completed flag. Clear this flag if you want to download again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_ResetCompletedFlag {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_ResetCompletedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select all item. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_SelectAll {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set completed flag. Set this flag if you do not want to download. This flag will be stored in the database and will not be downloaded again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_SetCompletedFlag {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_SetCompletedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start all items. If the number of items being downloaded exceeds the maximum number, start downloading later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_StartAll {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_StartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start selected items. If the number of items being downloaded exceeds the maximum number, start downloading later. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_StartSelected {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_StartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop all items. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_StopAll {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_StopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop selected items. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenu_Tooltips_StopSelected {
            get {
                return ResourceManager.GetString("MainMenu_Tooltips_StopSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %APP% is already executed! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_DupeExecute {
            get {
                return ResourceManager.GetString("MessageBox_DupeExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit %APP% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBox_DupeExecuteTitle {
            get {
                return ResourceManager.GetString("MessageBox_DupeExecuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Some videos have already been downloaded. Do you want to re-download them? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxAlreadyExistAskRedownload {
            get {
                return ResourceManager.GetString("MessageBoxAlreadyExistAskRedownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already downloaded に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxAlreadyExistAskRedownloadTitle {
            get {
                return ResourceManager.GetString("MessageBoxAlreadyExistAskRedownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxAskDelete {
            get {
                return ResourceManager.GetString("MessageBoxAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxAskDeleteTitle {
            get {
                return ResourceManager.GetString("MessageBoxAskDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find the configuration file. Do you want to initialize the settings? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxInitSetting_Text {
            get {
                return ResourceManager.GetString("MessageBoxInitSetting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initialize Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxInitSetting_Title {
            get {
                return ResourceManager.GetString("MessageBoxInitSetting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieve information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_AddNew_Text {
            get {
                return ResourceManager.GetString("Progress_AddNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieve information by clipboard auto detect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_DetectClipboard_Text {
            get {
                return ResourceManager.GetString("Progress_DetectClipboard_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieve information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_Subscribe_Text {
            get {
                return ResourceManager.GetString("Progress_Subscribe_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retrieve information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Progress_SubscribePrep_Text {
            get {
                return ResourceManager.GetString("Progress_SubscribePrep_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_ArgAddNewMenu_AddNew {
            get {
                return ResourceManager.GetString("SettingForm_ArgAddNewMenu_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add new arguments for yt-dlp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_ArgAddNewMenu_AddNew_Title {
            get {
                return ResourceManager.GetString("SettingForm_ArgAddNewMenu_AddNew_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_ArgAddNewMenu_Edit {
            get {
                return ResourceManager.GetString("SettingForm_ArgAddNewMenu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_ArgAddNewMenu_Remove {
            get {
                return ResourceManager.GetString("SettingForm_ArgAddNewMenu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit arguments for yt-dlp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_ArgEditMenu_Title {
            get {
                return ResourceManager.GetString("SettingForm_ArgEditMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select folder for media files output. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_SelectWorkFolder {
            get {
                return ResourceManager.GetString("SettingForm_SelectWorkFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select yt-dlp.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingForm_SelectYtdlpExe {
            get {
                return ResourceManager.GetString("SettingForm_SelectYtdlpExe", resourceCulture);
            }
        }
    }
}
